package com.yeyu.dao;

import com.yeyu.pojo.MenuAuth;
import java.util.List;

public interface MenuAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu_auth
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu_auth
     *
     * @mbg.generated
     */
    int insert(MenuAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu_auth
     *
     * @mbg.generated
     */
    MenuAuth selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu_auth
     *
     * @mbg.generated
     */
    List<MenuAuth> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu_auth
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MenuAuth record);
}