package com.yeyu.dao;

import com.yeyu.pojo.RequestLog;

public interface RequestLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_request_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_request_log
     *
     * @mbg.generated
     */
    int insert(RequestLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_request_log
     *
     * @mbg.generated
     */
    int insertSelective(RequestLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_request_log
     *
     * @mbg.generated
     */
    RequestLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_request_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RequestLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_request_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RequestLog record);
}