package com.yeyu.dao;

import com.yeyu.pojo.RoleMenu;

public interface RoleMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_rolemenu
     *
     * @mbg.generated
     */
    int insert(RoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_rolemenu
     *
     * @mbg.generated
     */
    int insertSelective(RoleMenu record);
}